# Generated by Django 4.0.6 on 2022-07-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variationvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationvalue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variation_image'),
        ),
    ]
